In [ ]:
import numpy as np

In [ ]:
Test_c_grad=np.load('Test_c_grad.npy')
values=np.load('values.npy')
Test_c_grad=np.round(Test_c_grad*45)

In [ ]:
Test_c_grad.shape

In [ ]:
np.max(Test_c_grad)

In [ ]:
values.shape

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
#plt.figure(figsize=(8,8))
f, axs = plt.subplots(figsize=(14,8),nrows=1,ncols=1)
sns.heatmap(values[0],annot=True,ax=axs,fmt='g').invert_yaxis()

In [ ]:
data=Test_c_grad[0,4,3,0]

In [ ]:
f, axs = plt.subplots(figsize=(14,8),nrows=1,ncols=1)
sns.heatmap(data,annot=True,ax=axs,fmt='g').invert_yaxis()

In [ ]:
output.shape

In [ ]:
output=np.reshape(output,(-1,2,21,12))

In [ ]:
f, axs = plt.subplots(figsize=(14,8),nrows=1,ncols=1)
sns.heatmap(output[10,1],annot=True,ax=axs,fmt='g').invert_yaxis()

In [1]:
import numpy as np
from hmmlearn import hmm

states = ["box 1", "box 2", "box3"]
n_states = len(states)

observations = ["red", "white"]
n_observations = len(observations)

start_probability = np.array([0.2, 0.4, 0.4])

transition_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.3, 0.5, 0.2],
  [0.2, 0.3, 0.5]
])

emission_probability = np.array([
  [0.5, 0.5],
  [0.4, 0.6],
  [0.7, 0.3]
])

model = hmm.MultinomialHMM(n_components=n_states)
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

In [5]:
seen = np.array([[0,1,0]]).T
logprob, box = model.decode(seen, algorithm="viterbi")
box

array([2, 2, 2])

In [7]:
np.exp(logprob)

0.014699999999999996

观测：红 白 红

预测隐变量 ：box 3 box 3 box 3

In [31]:
import numpy as np
from hmmlearn import hmm

states = ["box 1", "box 2", "box 3"]
n_states = len(states)

observations = ["red", "white"]
n_observations = len(observations)
model2 = hmm.MultinomialHMM(n_components=n_states, n_iter=20, tol=0.001)
X2 = np.array([[0,1,0,2],[0,0,2,1],[1,0,1,1],[1,0,1,1],[1,0,1,1]])
model2.fit(X2)
print(model2.startprob_    )
# print(model2.transmat_     )
# print(model2.emissionprob_ )
# print(model2.score(X2)     )

[3.78111685e-20 1.29525598e-66 1.00000000e+00]


In [32]:
print(model2.transmat_ )

[[5.24717415e-01 5.17321851e-05 4.75230853e-01]
 [7.45273836e-01 4.71594545e-04 2.54254569e-01]
 [1.98498023e-01 7.01746957e-01 9.97550198e-02]]


In [33]:
print(model2.emissionprob_ )

[[5.10086336e-02 9.48991344e-01 2.27072708e-08]
 [1.25600487e-16 5.65262565e-01 4.34737435e-01]
 [9.99384886e-01 6.15114160e-04 5.92222889e-13]]


In [34]:
print(np.exp(model2.score(X2)) )

4.221498228900331e-07


In [35]:
startprob = np.array([0.6, 0.3, 0.1, 0.0])
# The transition matrix, note that there are no transitions possible
# between component 1 and 3
transmat = np.array([[0.7, 0.2, 0.0, 0.1],
                     [0.3, 0.5, 0.2, 0.0],
                     [0.0, 0.3, 0.5, 0.2],
                     [0.2, 0.0, 0.2, 0.6]])
# The means of each component
means = np.array([[0.0,  0.0],
                  [0.0, 11.0],
                  [9.0, 10.0],
                  [11.0, -1.0]])
# The covariance of each component
covars = .5 * np.tile(np.identity(2), (4, 1, 1))

# Build an HMM instance and set parameters
model3 = hmm.GaussianHMM(n_components=4, covariance_type="full")

# Instead of fitting it from the data, we directly set the estimated
# parameters, the means and covariance of the components
model3.startprob_ = startprob
model3.transmat_ = transmat
model3.means_ = means
model3.covars_ = covars

In [36]:
seen = np.array([[1.1,2.0],[-1,2.0],[3,7]])
logprob, state = model3.decode(seen, algorithm="viterbi")

In [37]:
state

array([0, 0, 1])

In [40]:
np.exp(logprob)

1.3845892651603015e-18